baseurl = "https://mantrabio.com"
languageCode = "en-us"
languageLang = "en"
title = "Mantra Bio"

# RSS, categories and tags disabled for an easy start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
