backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    preview: false
    folder: "site/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "pages"
    label: "Pages"
    preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Page title", name: title, widget: string}
          - {label: "Header text", name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Overview", name: overview, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: Image, name: image, widget: image},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Highlights", name: items, widget: list, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Outro", name: "outro", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Link", name: "link", widget: string, required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}
          - {label: "Careers", name: "careers", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Button label", name: "buttonText", widget: "string"}]}
      - file: "site/content/science/_index.md"
        label: "Science Page"
        name: "science"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "description", widget: markdown}]}
          - {label: "Approach", name: "approach", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Above graphic", name: "before", widget: markdown},
              {label: "Below graphic", name: "after", widget: markdown, required: false}]}
          - {label: "Highlight 1", name: "part1", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "description", widget: markdown}]}
          - {label: "Highlight 2", name: "part2", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "description", widget: markdown},
              {label: "Button link", name: "link", widget: "string", required: false},
              {label: "Button label", name: "linklabel", widget: "string", required: false}]}
      - file: "site/content/partnering/_index.md"
        label: "Partnering Page"
        name: "partnering"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: before, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: Image, name: image, widget: image},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Overview", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Highlights", name: items, widget: list, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Outro", name: "after", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/team/_index.md"
        label: "Team Page"
        name: "team"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image}
          - {label: "Employees", name: employees, widget: list, fields: [
              {label: "Name", name: "name", widget: string},
              {label: "Title", name: "title", widget: string},
              {label: Image, name: image, widget: image},
              {label: "Bio", name: "bio", widget: "markdown"},
              {label: "Link", name: "link", widget: "string"}]}
          - {label: "Advisors", name: advisors, widget: list, fields: [
              {label: "Name", name: "name", widget: string},
              {label: "Affiliation", name: "affiliation", widget: string},
              {label: Image, name: image, widget: image},
              {label: "Bio", name: "bio", widget: "markdown"},
              {label: "Link", name: "link", widget: "string"}]}
          - {label: "Investors", name: investors, widget: list, fields: [
              {label: Image, name: image, widget: image}]}
      - file: "site/content/careers/_index.md"
        label: "Careers Page"
        name: "careers"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image}
          - {label: Values, name: values, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: markdown},
              {label: Image, name: imageUrl, widget: image}]}
          - {label: Values diagram, name: diagram, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: text},
              {label: Image, name: imageUrl, widget: image},
              {label: "Value 1", name: value1, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 2", name: value2, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 3", name: value3, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 4", name: value4, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 5", name: value5, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 6", name: value6, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]},
              {label: "Value 7", name: value7, widget: object, fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Text", name: "text", widget: "text"}]}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
                required: false
              - label: Text
                name: text
                widget: text